spring:
  application:
    name: ai-code-mother-backend
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ai_code
#    username: root
#    password: LZNlzn123.
#
#      # Redis 配置
  data:
    redis:
      database: ${spring.data.redis.database}
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}
      timeout: ${spring.data.redis.timeout}
      ttl: ${spring.data.redis.ttl}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  session:
    timeout: 2592000
  profiles:
    active: dev
server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        # session过期时间30天
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.limou.aicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
cos:
  client:
    region: ${cos.client.region}
    secretId: ${cos.client.secretId}
    secretKey: ${cos.client.secretKey}
    host: ${cos.client.host}
    bucket: ${cos.client.bucket}
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: ${langchain4j.open-ai.chat-model.api-key}
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
#      strict-json-schema: true
#      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: ${langchain4j.open-ai.chat-model.api-key}
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
    reason-stream-chat-model:
      base-url: https://api.deepseek.com
      api-key: ${langchain4j.open-ai.chat-model.api-key}
      model-name: deepseek-chat
      max-tokens: 8192

# Pexels 图片搜索配置
pexels:
  api-key: ${pexels.api-key}
